import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import {Button } from '@mui/material'
// import {} from '@mui/icons-material'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button>click here</Button>
      <Button color='primary'>click here</Button>
      <Button color='secondary' variant='outline' >click here</Button>
      <Button color='success' variant='contained' >click here</Button>
      <Button color='error' variant='contained' >click here</Button>
      <Button color='info' variant='contained' onClick={() => {
        alert('clicked')
      }} >click me</Button>

      
      
    </div>
  )
}
